version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - "./backend/src:/app/src"
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - "./frontend/src:/app/src"
    links:
      - backend
